
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfExigencia;
import org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfExigenciaMensagem;
import org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfPedido;
import org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfPropriedadeDominio;
import org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRepasse;
import org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ecartorio_service.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param nuRequisicao
     * @param dtPagamentoIni
     * @param idServico
     * @param dtPedidoIni
     * @param statusPedido
     * @param dtPedidoFin
     * @param idCerp
     * @param tipoAto
     * @param dtStatusPedidoInicial
     * @param nuCpfCnpj
     * @param dsPdStatusPedidoExt
     * @param dtStatusPedidoFinal
     * @param dtPagamentoFin
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfPedido
     */
    @WebMethod(action = "http://tempuri.org/IService/listarPedidos")
    @WebResult(name = "listarPedidosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarPedidos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarPedidos")
    @ResponseWrapper(localName = "listarPedidosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarPedidosResponse")
    public ArrayOfPedido listarPedidos(
        @WebParam(name = "id_servico", targetNamespace = "http://tempuri.org/")
        String idServico,
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "ds_pd_status_pedido_ext", targetNamespace = "http://tempuri.org/")
        String dsPdStatusPedidoExt,
        @WebParam(name = "dt_pedido_ini", targetNamespace = "http://tempuri.org/")
        String dtPedidoIni,
        @WebParam(name = "dt_pedido_fin", targetNamespace = "http://tempuri.org/")
        String dtPedidoFin,
        @WebParam(name = "nu_cpf_cnpj", targetNamespace = "http://tempuri.org/")
        String nuCpfCnpj,
        @WebParam(name = "nu_requisicao", targetNamespace = "http://tempuri.org/")
        String nuRequisicao,
        @WebParam(name = "tipo_ato", targetNamespace = "http://tempuri.org/")
        String tipoAto,
        @WebParam(name = "status_pedido", targetNamespace = "http://tempuri.org/")
        String statusPedido,
        @WebParam(name = "dt_status_pedido_inicial", targetNamespace = "http://tempuri.org/")
        String dtStatusPedidoInicial,
        @WebParam(name = "dt_status_pedido_final", targetNamespace = "http://tempuri.org/")
        String dtStatusPedidoFinal,
        @WebParam(name = "dt_pagamento_ini", targetNamespace = "http://tempuri.org/")
        String dtPagamentoIni,
        @WebParam(name = "dt_pagamento_fin", targetNamespace = "http://tempuri.org/")
        String dtPagamentoFin);

    /**
     * 
     * @param dtRepasseInicial
     * @param idCerp
     * @param idServico
     * @param modelo
     * @param dtRepasseFinal
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRepasse
     */
    @WebMethod(action = "http://tempuri.org/IService/listarRepasses")
    @WebResult(name = "listarRepassesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarRepasses", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarRepasses")
    @ResponseWrapper(localName = "listarRepassesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarRepassesResponse")
    public ArrayOfRepasse listarRepasses(
        @WebParam(name = "id_servico", targetNamespace = "http://tempuri.org/")
        String idServico,
        @WebParam(name = "dt_repasse_inicial", targetNamespace = "http://tempuri.org/")
        String dtRepasseInicial,
        @WebParam(name = "dt_repasse_final", targetNamespace = "http://tempuri.org/")
        String dtRepasseFinal,
        @WebParam(name = "modelo", targetNamespace = "http://tempuri.org/")
        String modelo,
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp);

    /**
     * 
     * @param dsPdTipoPedido
     * @param dsPdTipoDoc
     * @param nuValor
     * @param nuRgi
     * @param dsPdFinalidade
     * @param idRequisicao
     * @param nmNaturezaAto
     * @param dtSla
     * @param nuAto
     * @param nuNumeroB
     * @param nmMae
     * @param nuNumeroA
     * @param dsLogradouro
     * @param nuFolha
     * @param nmBusca
     * @param nmPai
     * @param nmLivro
     * @param nuCpfCnpjBusca
     * @param dtAto
     * @param dsBairro
     * @param cdOrigem
     * @param dsObsAto
     * @param dsPdTipoAto
     * @param idServico
     * @param tpLogradouro
     * @param nuLogradouro
     * @param dsComplementoA
     * @param nuCpfCnpj
     * @param dsComplementoB
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno
     */
    @WebMethod(action = "http://tempuri.org/IService/gerarPedido")
    @WebResult(name = "gerarPedidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "gerarPedido", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GerarPedido")
    @ResponseWrapper(localName = "gerarPedidoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GerarPedidoResponse")
    public ArrayOfRetorno gerarPedido(
        @WebParam(name = "nu_cpf_cnpj", targetNamespace = "http://tempuri.org/")
        String nuCpfCnpj,
        @WebParam(name = "id_servico", targetNamespace = "http://tempuri.org/")
        String idServico,
        @WebParam(name = "ds_pd_tipo_pedido", targetNamespace = "http://tempuri.org/")
        String dsPdTipoPedido,
        @WebParam(name = "ds_pd_tipo_ato", targetNamespace = "http://tempuri.org/")
        String dsPdTipoAto,
        @WebParam(name = "ds_pd_tipo_doc", targetNamespace = "http://tempuri.org/")
        String dsPdTipoDoc,
        @WebParam(name = "ds_pd_finalidade", targetNamespace = "http://tempuri.org/")
        String dsPdFinalidade,
        @WebParam(name = "id_requisicao", targetNamespace = "http://tempuri.org/")
        String idRequisicao,
        @WebParam(name = "dt_sla", targetNamespace = "http://tempuri.org/")
        String dtSla,
        @WebParam(name = "cd_origem", targetNamespace = "http://tempuri.org/")
        String cdOrigem,
        @WebParam(name = "nu_rgi", targetNamespace = "http://tempuri.org/")
        String nuRgi,
        @WebParam(name = "tp_logradouro", targetNamespace = "http://tempuri.org/")
        String tpLogradouro,
        @WebParam(name = "ds_logradouro", targetNamespace = "http://tempuri.org/")
        String dsLogradouro,
        @WebParam(name = "nu_logradouro", targetNamespace = "http://tempuri.org/")
        String nuLogradouro,
        @WebParam(name = "nu_numero_a", targetNamespace = "http://tempuri.org/")
        String nuNumeroA,
        @WebParam(name = "ds_complemento_a", targetNamespace = "http://tempuri.org/")
        String dsComplementoA,
        @WebParam(name = "nu_numero_b", targetNamespace = "http://tempuri.org/")
        String nuNumeroB,
        @WebParam(name = "ds_complemento_b", targetNamespace = "http://tempuri.org/")
        String dsComplementoB,
        @WebParam(name = "ds_bairro", targetNamespace = "http://tempuri.org/")
        String dsBairro,
        @WebParam(name = "nm_busca", targetNamespace = "http://tempuri.org/")
        String nmBusca,
        @WebParam(name = "nu_cpf_cnpj_busca", targetNamespace = "http://tempuri.org/")
        String nuCpfCnpjBusca,
        @WebParam(name = "nm_pai", targetNamespace = "http://tempuri.org/")
        String nmPai,
        @WebParam(name = "nm_mae", targetNamespace = "http://tempuri.org/")
        String nmMae,
        @WebParam(name = "nm_livro", targetNamespace = "http://tempuri.org/")
        String nmLivro,
        @WebParam(name = "nu_folha", targetNamespace = "http://tempuri.org/")
        String nuFolha,
        @WebParam(name = "nm_natureza_ato", targetNamespace = "http://tempuri.org/")
        String nmNaturezaAto,
        @WebParam(name = "dt_ato", targetNamespace = "http://tempuri.org/")
        String dtAto,
        @WebParam(name = "ds_obs_ato", targetNamespace = "http://tempuri.org/")
        String dsObsAto,
        @WebParam(name = "nu_ato", targetNamespace = "http://tempuri.org/")
        String nuAto,
        @WebParam(name = "nu_valor", targetNamespace = "http://tempuri.org/")
        String nuValor);

    /**
     * 
     * @param cdOrigem
     * @param idCerp
     * @param idServico
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno
     */
    @WebMethod(action = "http://tempuri.org/IService/marcarPedidoCartorio")
    @WebResult(name = "marcarPedidoCartorioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "marcarPedidoCartorio", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarcarPedidoCartorio")
    @ResponseWrapper(localName = "marcarPedidoCartorioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarcarPedidoCartorioResponse")
    public ArrayOfRetorno marcarPedidoCartorio(
        @WebParam(name = "id_servico", targetNamespace = "http://tempuri.org/")
        String idServico,
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "cd_origem", targetNamespace = "http://tempuri.org/")
        String cdOrigem);

    /**
     * 
     * @param idCerp
     * @param dsStatus
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno
     */
    @WebMethod(action = "http://tempuri.org/IService/marcarStatus")
    @WebResult(name = "marcarStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "marcarStatus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarcarStatus")
    @ResponseWrapper(localName = "marcarStatusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarcarStatusResponse")
    public ArrayOfRetorno marcarStatus(
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "ds_status", targetNamespace = "http://tempuri.org/")
        String dsStatus);

    /**
     * 
     * @param cdDominio
     * @param idDominioPai
     * @param propriedade
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfPropriedadeDominio
     */
    @WebMethod(action = "http://tempuri.org/IService/listarPropriedade")
    @WebResult(name = "listarPropriedadeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarPropriedade", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarPropriedade")
    @ResponseWrapper(localName = "listarPropriedadeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarPropriedadeResponse")
    public ArrayOfPropriedadeDominio listarPropriedade(
        @WebParam(name = "propriedade", targetNamespace = "http://tempuri.org/")
        String propriedade,
        @WebParam(name = "cd_dominio", targetNamespace = "http://tempuri.org/")
        String cdDominio,
        @WebParam(name = "id_dominio_pai", targetNamespace = "http://tempuri.org/")
        String idDominioPai);

    /**
     * 
     * @param dtConclusaoIni
     * @param dtExigenciaIni
     * @param idCerp
     * @param idServico
     * @param nuCpfCnpj
     * @param dtConclusaoFin
     * @param dtExigenciaFin
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfExigencia
     */
    @WebMethod(action = "http://tempuri.org/IService/listarExigencia")
    @WebResult(name = "listarExigenciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarExigencia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarExigencia")
    @ResponseWrapper(localName = "listarExigenciaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarExigenciaResponse")
    public ArrayOfExigencia listarExigencia(
        @WebParam(name = "id_servico", targetNamespace = "http://tempuri.org/")
        String idServico,
        @WebParam(name = "nu_cpf_cnpj", targetNamespace = "http://tempuri.org/")
        String nuCpfCnpj,
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "dt_exigencia_ini", targetNamespace = "http://tempuri.org/")
        String dtExigenciaIni,
        @WebParam(name = "dt_exigencia_fin", targetNamespace = "http://tempuri.org/")
        String dtExigenciaFin,
        @WebParam(name = "dt_conclusao_ini", targetNamespace = "http://tempuri.org/")
        String dtConclusaoIni,
        @WebParam(name = "dt_conclusao_fin", targetNamespace = "http://tempuri.org/")
        String dtConclusaoFin);

    /**
     * 
     * @param nuExigencia
     * @param dtExigenciaInicial
     * @param idCerp
     * @param flMensagemLida
     * @param dtExigenciaFinal
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfExigenciaMensagem
     */
    @WebMethod(action = "http://tempuri.org/IService/listarExigenciaMensagem")
    @WebResult(name = "listarExigenciaMensagemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarExigenciaMensagem", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarExigenciaMensagem")
    @ResponseWrapper(localName = "listarExigenciaMensagemResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarExigenciaMensagemResponse")
    public ArrayOfExigenciaMensagem listarExigenciaMensagem(
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "nu_exigencia", targetNamespace = "http://tempuri.org/")
        String nuExigencia,
        @WebParam(name = "dt_exigencia_inicial", targetNamespace = "http://tempuri.org/")
        String dtExigenciaInicial,
        @WebParam(name = "dt_exigencia_final", targetNamespace = "http://tempuri.org/")
        String dtExigenciaFinal,
        @WebParam(name = "fl_mensagem_lida", targetNamespace = "http://tempuri.org/")
        String flMensagemLida);

    /**
     * 
     * @param nuValor
     * @param dsExigencia
     * @param idCerp
     * @param dtPrazoConclusao
     * @param flTpFinanceiro
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno
     */
    @WebMethod(action = "http://tempuri.org/IService/marcarExigencia")
    @WebResult(name = "marcarExigenciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "marcarExigencia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarcarExigencia")
    @ResponseWrapper(localName = "marcarExigenciaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarcarExigenciaResponse")
    public ArrayOfRetorno marcarExigencia(
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "ds_exigencia", targetNamespace = "http://tempuri.org/")
        String dsExigencia,
        @WebParam(name = "dt_prazo_conclusao", targetNamespace = "http://tempuri.org/")
        String dtPrazoConclusao,
        @WebParam(name = "fl_tp_financeiro", targetNamespace = "http://tempuri.org/")
        String flTpFinanceiro,
        @WebParam(name = "nu_valor", targetNamespace = "http://tempuri.org/")
        String nuValor);

    /**
     * 
     * @param nuExigencia
     * @param idCerp
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno
     */
    @WebMethod(action = "http://tempuri.org/IService/cumprirExigencia")
    @WebResult(name = "cumprirExigenciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "cumprirExigencia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CumprirExigencia")
    @ResponseWrapper(localName = "cumprirExigenciaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CumprirExigenciaResponse")
    public ArrayOfRetorno cumprirExigencia(
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "nu_exigencia", targetNamespace = "http://tempuri.org/")
        String nuExigencia);

    /**
     * 
     * @param nuExigencia
     * @param idCerp
     * @param dsResposta
     * @return
     *     returns org.datacontract.schemas._2004._07.ecartorio_service.ArrayOfRetorno
     */
    @WebMethod(action = "http://tempuri.org/IService/responderExigencia")
    @WebResult(name = "responderExigenciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "responderExigencia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResponderExigencia")
    @ResponseWrapper(localName = "responderExigenciaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResponderExigenciaResponse")
    public ArrayOfRetorno responderExigencia(
        @WebParam(name = "id_cerp", targetNamespace = "http://tempuri.org/")
        String idCerp,
        @WebParam(name = "ds_resposta", targetNamespace = "http://tempuri.org/")
        String dsResposta,
        @WebParam(name = "nu_exigencia", targetNamespace = "http://tempuri.org/")
        String nuExigencia);

}
