-- DROP TABLE MP_SISTEMA_CONFIG;
-- CREATE TABLE MP_SISTEMA_CONFIG (ID BIGINT NOT NULL, IND_ATIVO BOOLEAN, IND_EXCLUSAO BOOLEAN, DTHR_ALT TIMESTAMP, DTHR_INC TIMESTAMP, USER_ALT VARCHAR(100), USER_INC VARCHAR(100), TENANT_ID VARCHAR(255) NOT NULL, VERSION INTEGER DEFAULT 0 NOT NULL, DESCRICAO VARCHAR(255) NOT NULL, INDVALOR BOOLEAN NOT NULL, MPTIPOCAMPO INTEGER NOT NULL, OBJETO VARCHAR(30), PARAMETRO VARCHAR(100) NOT NULL, VALORN INTEGER NOT NULL, VALORT VARCHAR(1000) NOT NULL, PRIMARY KEY (ID));

INSERT INTO MP_SISTEMA_CONFIG (ID, IND_ATIVO, IND_EXCLUSAO, DTHR_ALT, DTHR_INC, USER_ALT, USER_INC, TENANT_ID, VERSION, DESCRICAO, INDVALOR, MPTIPOCAMPO, OBJETO, PARAMETRO, VALORN, VALORT) VALUES
 (29, true, false, null, '2016-08-07 11:21:24', null, null, '0', 0, 'Caminho(Path) recebimento arquivo TXT', true, 1, '', 'oficPathRecebeTXT', 0, 'C:\\RECEBE_TXT\\');
INSERT INTO MP_SISTEMA_CONFIG (ID, IND_ATIVO, IND_EXCLUSAO, DTHR_ALT, DTHR_INC, USER_ALT, USER_INC, TENANT_ID, VERSION, DESCRICAO, INDVALOR, MPTIPOCAMPO, OBJETO, PARAMETRO, VALORN, VALORT) VALUES
 (30, true, false, null, '2016-08-07 11:21:24', null, null, '0', 0, 'Caminho(Path) recebimento arquivo ATO', true, 1, '', 'oficPathRecebeATO', 0, 'C:\\RECEBE_ATO\\');
INSERT INTO MP_SISTEMA_CONFIG (ID, IND_ATIVO, IND_EXCLUSAO, DTHR_ALT, DTHR_INC, USER_ALT, USER_INC, TENANT_ID, VERSION, DESCRICAO, INDVALOR, MPTIPOCAMPO, OBJETO, PARAMETRO, VALORN, VALORT) VALUES
 (31, true, false, null, '2016-08-07 11:21:24', null, null, '0', 0, 'Ativa Exibicao Label nos Campos', true, 1, '', 'indLabelCampo', 0, '');
