package com.mpxds.mpbasic.model.enums;

public enum MpTipoProdutoCategoria {

	MEDICAMENTOS_01_000(MpTipoProduto.MEDICAMENTOS, "Alergias e Infecções", null),
	MEDICAMENTOS_01_001(MpTipoProduto.MEDICAMENTOS, "Antialérgicos", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_002(MpTipoProduto.MEDICAMENTOS, "Antibióticos", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_003(MpTipoProduto.MEDICAMENTOS, "Antiviral", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_004(MpTipoProduto.MEDICAMENTOS, "Asma", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_005(MpTipoProduto.MEDICAMENTOS, "Dermatites", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_006(MpTipoProduto.MEDICAMENTOS, "Imunoestimulantes", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_007(MpTipoProduto.MEDICAMENTOS, "Imunossupressor", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_008(MpTipoProduto.MEDICAMENTOS, "Problemas Respiratórios", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_01_009(MpTipoProduto.MEDICAMENTOS, "Problemas Renais", MpTipoProdutoCategoria.MEDICAMENTOS_01_000),
	MEDICAMENTOS_011_000(MpTipoProduto.MEDICAMENTOS, "Circulação", null),
	MEDICAMENTOS_011_001(MpTipoProduto.MEDICAMENTOS, "Antiagregante Plaquetário", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_002(MpTipoProduto.MEDICAMENTOS, "Anticoagulante", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_003(MpTipoProduto.MEDICAMENTOS, "Cardiovasculares", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_004(MpTipoProduto.MEDICAMENTOS, "Coagulação", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_005(MpTipoProduto.MEDICAMENTOS, "Trombose", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_006(MpTipoProduto.MEDICAMENTOS, "Varizes", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_007(MpTipoProduto.MEDICAMENTOS, "Vasodilatador", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_008(MpTipoProduto.MEDICAMENTOS, "Hipotensor", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_011_009(MpTipoProduto.MEDICAMENTOS, "Colesterol e Triglicerídeos", MpTipoProdutoCategoria.MEDICAMENTOS_011_000),
	MEDICAMENTOS_02_000(MpTipoProduto.MEDICAMENTOS, "Diabetes", null),
	MEDICAMENTOS_02_001(MpTipoProduto.MEDICAMENTOS, "Hipoglicemiante", MpTipoProdutoCategoria.MEDICAMENTOS_02_000),
	MEDICAMENTOS_03_000(MpTipoProduto.MEDICAMENTOS, "Digestão e Regulador Intestinal", null),
	MEDICAMENTOS_03_001(MpTipoProduto.MEDICAMENTOS, "Antiácidos", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_002(MpTipoProduto.MEDICAMENTOS, "Antiespasmódico", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_003(MpTipoProduto.MEDICAMENTOS, "Antigases", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_004(MpTipoProduto.MEDICAMENTOS, "Diarreia", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_005(MpTipoProduto.MEDICAMENTOS, "Digestivos", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_006(MpTipoProduto.MEDICAMENTOS, "Hemorroidas", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_007(MpTipoProduto.MEDICAMENTOS, "Hepatoprotetor", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_008(MpTipoProduto.MEDICAMENTOS, "Laxantes", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_009(MpTipoProduto.MEDICAMENTOS, "Náuseas", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_010(MpTipoProduto.MEDICAMENTOS, "Regulador Intestinal", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_011(MpTipoProduto.MEDICAMENTOS, "Reidratantes", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_012(MpTipoProduto.MEDICAMENTOS, "Síndrome do Intestino Irritável", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_03_013(MpTipoProduto.MEDICAMENTOS, "Úlcera e Gastrite", MpTipoProdutoCategoria.MEDICAMENTOS_03_000),
	MEDICAMENTOS_031_000(MpTipoProduto.MEDICAMENTOS, "Doença dos Ossos", null),
	MEDICAMENTOS_031_001(MpTipoProduto.MEDICAMENTOS, "Articulações", MpTipoProdutoCategoria.MEDICAMENTOS_031_000),
	MEDICAMENTOS_031_002(MpTipoProduto.MEDICAMENTOS, "Artrite/Artrose", MpTipoProdutoCategoria.MEDICAMENTOS_031_000),
	MEDICAMENTOS_031_003(MpTipoProduto.MEDICAMENTOS, "Osteoporose", MpTipoProdutoCategoria.MEDICAMENTOS_031_000),
	MEDICAMENTOS_031_004(MpTipoProduto.MEDICAMENTOS, "Vitaminas.", MpTipoProdutoCategoria.MEDICAMENTOS_031_000),
	MEDICAMENTOS_04_000(MpTipoProduto.MEDICAMENTOS, "Dor e Contusão", null),
	MEDICAMENTOS_04_001(MpTipoProduto.MEDICAMENTOS, "Analgésicos e Antitérmicos", MpTipoProdutoCategoria.MEDICAMENTOS_04_000),
	MEDICAMENTOS_04_002(MpTipoProduto.MEDICAMENTOS, "Anti-inflamatórios e Relaxante Muscular", MpTipoProdutoCategoria.MEDICAMENTOS_04_000),
	MEDICAMENTOS_04_003(MpTipoProduto.MEDICAMENTOS, "Contusão", MpTipoProdutoCategoria.MEDICAMENTOS_04_000),
	MEDICAMENTOS_04_004(MpTipoProduto.MEDICAMENTOS, "Dor de Garganta", MpTipoProdutoCategoria.MEDICAMENTOS_04_000),
	MEDICAMENTOS_04_005(MpTipoProduto.MEDICAMENTOS, "Enxaqueca", MpTipoProdutoCategoria.MEDICAMENTOS_04_000),
	MEDICAMENTOS_041_000(MpTipoProduto.MEDICAMENTOS, "Genéricos", null),
	MEDICAMENTOS_041_001(MpTipoProduto.MEDICAMENTOS, "Colesterol e Triglicerídeos.", MpTipoProdutoCategoria.MEDICAMENTOS_041_000),
	MEDICAMENTOS_041_002(MpTipoProduto.MEDICAMENTOS, "Redutores de Peso.", MpTipoProdutoCategoria.MEDICAMENTOS_041_000),
	MEDICAMENTOS_05_000(MpTipoProduto.MEDICAMENTOS, "Gripes e Resfriados", null),
	MEDICAMENTOS_05_001(MpTipoProduto.MEDICAMENTOS, "Antigripais", MpTipoProdutoCategoria.MEDICAMENTOS_05_000),
	MEDICAMENTOS_05_002(MpTipoProduto.MEDICAMENTOS, "Descongestionante", MpTipoProdutoCategoria.MEDICAMENTOS_05_000),
	MEDICAMENTOS_05_003(MpTipoProduto.MEDICAMENTOS, "Descongestionante Nasal", MpTipoProdutoCategoria.MEDICAMENTOS_05_000),
	MEDICAMENTOS_05_004(MpTipoProduto.MEDICAMENTOS, "Naturais", MpTipoProdutoCategoria.MEDICAMENTOS_05_000),
	MEDICAMENTOS_05_005(MpTipoProduto.MEDICAMENTOS, "Tosse", MpTipoProdutoCategoria.MEDICAMENTOS_05_000),
	MEDICAMENTOS_051_000(MpTipoProduto.MEDICAMENTOS, "Hormônios", null),
	MEDICAMENTOS_051_001(MpTipoProduto.MEDICAMENTOS, "Antiandrogênico", MpTipoProdutoCategoria.MEDICAMENTOS_051_000),
	MEDICAMENTOS_051_002(MpTipoProduto.MEDICAMENTOS, "Gota", MpTipoProdutoCategoria.MEDICAMENTOS_051_000),
	MEDICAMENTOS_051_003(MpTipoProduto.MEDICAMENTOS, "Inibidor de Prolactina", MpTipoProdutoCategoria.MEDICAMENTOS_051_000),
	MEDICAMENTOS_051_004(MpTipoProduto.MEDICAMENTOS, "Reposição Hormonal", MpTipoProdutoCategoria.MEDICAMENTOS_051_000),
	MEDICAMENTOS_051_005(MpTipoProduto.MEDICAMENTOS, "Tireóide", MpTipoProdutoCategoria.MEDICAMENTOS_051_000),
	MEDICAMENTOS_06_000(MpTipoProduto.MEDICAMENTOS, "Olhos", null),
	MEDICAMENTOS_06_001(MpTipoProduto.MEDICAMENTOS, "Alergia e Infecções", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_002(MpTipoProduto.MEDICAMENTOS, "Catarata", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_003(MpTipoProduto.MEDICAMENTOS, "Dilatador de Pupilas", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_004(MpTipoProduto.MEDICAMENTOS, "Lentes de Contato", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_005(MpTipoProduto.MEDICAMENTOS, "Limpeza", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_006(MpTipoProduto.MEDICAMENTOS, "Lubrificantes", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_007(MpTipoProduto.MEDICAMENTOS, "Lupa e Protetor", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_06_008(MpTipoProduto.MEDICAMENTOS, "Vitaminas", MpTipoProdutoCategoria.MEDICAMENTOS_06_000),
	MEDICAMENTOS_061_000(MpTipoProduto.MEDICAMENTOS, "Ouvido", null),
	MEDICAMENTOS_061_001(MpTipoProduto.MEDICAMENTOS, "Analgésico e Anti-inflamatório.", MpTipoProdutoCategoria.MEDICAMENTOS_061_000),
	MEDICAMENTOS_061_002(MpTipoProduto.MEDICAMENTOS, "Antibiótico.", MpTipoProdutoCategoria.MEDICAMENTOS_061_000),
	MEDICAMENTOS_061_003(MpTipoProduto.MEDICAMENTOS, "Cera", MpTipoProdutoCategoria.MEDICAMENTOS_061_000),
	MEDICAMENTOS_062_000(MpTipoProduto.MEDICAMENTOS, "Pare de Fumar", null),
	MEDICAMENTOS_062_001(MpTipoProduto.MEDICAMENTOS, "Adesivos", MpTipoProdutoCategoria.MEDICAMENTOS_062_000),
	MEDICAMENTOS_062_002(MpTipoProduto.MEDICAMENTOS, "Antitabagismo", MpTipoProdutoCategoria.MEDICAMENTOS_062_000),
	MEDICAMENTOS_062_003(MpTipoProduto.MEDICAMENTOS, "Gomas e Pastilhas", MpTipoProdutoCategoria.MEDICAMENTOS_062_000),
	MEDICAMENTOS_07_000(MpTipoProduto.MEDICAMENTOS, "Pele e Mucosas", null),
	MEDICAMENTOS_07_001(MpTipoProduto.MEDICAMENTOS, "Acne", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_002(MpTipoProduto.MEDICAMENTOS, "Afta", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_003(MpTipoProduto.MEDICAMENTOS, "Anestésicos", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_004(MpTipoProduto.MEDICAMENTOS, "Antimicóticos e Fungos", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_005(MpTipoProduto.MEDICAMENTOS, "Antineoplásico", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_006(MpTipoProduto.MEDICAMENTOS, "Assadura", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_007(MpTipoProduto.MEDICAMENTOS, "Calos e Verrugas", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_008(MpTipoProduto.MEDICAMENTOS, "Cicatrizantes", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_009(MpTipoProduto.MEDICAMENTOS, "Despigmentador", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_010(MpTipoProduto.MEDICAMENTOS, "Herpes", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_011(MpTipoProduto.MEDICAMENTOS, "Queloide", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_07_012(MpTipoProduto.MEDICAMENTOS, "Vitiligo", MpTipoProdutoCategoria.MEDICAMENTOS_07_000),
	MEDICAMENTOS_08_000(MpTipoProduto.MEDICAMENTOS, "Pressão Alta", null),
	MEDICAMENTOS_08_001(MpTipoProduto.MEDICAMENTOS, "Anti-hipertensivo", MpTipoProdutoCategoria.MEDICAMENTOS_08_000),
	MEDICAMENTOS_08_002(MpTipoProduto.MEDICAMENTOS, "Diuréticos", MpTipoProdutoCategoria.MEDICAMENTOS_08_000),
	MEDICAMENTOS_081_000(MpTipoProduto.MEDICAMENTOS, "Primeiros Socorros", null),
	MEDICAMENTOS_081_001(MpTipoProduto.MEDICAMENTOS, "Agulhas e Seringas", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_002(MpTipoProduto.MEDICAMENTOS, "Assepsia", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_003(MpTipoProduto.MEDICAMENTOS, "Atadura e Gaze", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_004(MpTipoProduto.MEDICAMENTOS, "Curativos", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_005(MpTipoProduto.MEDICAMENTOS, "Descartex", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_006(MpTipoProduto.MEDICAMENTOS, "Equipo", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_007(MpTipoProduto.MEDICAMENTOS, "Esparadrapo", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_008(MpTipoProduto.MEDICAMENTOS, "Luva Cirúrgica", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_009(MpTipoProduto.MEDICAMENTOS, "Porta Comprimidos", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_010(MpTipoProduto.MEDICAMENTOS, "Soro Fisiológico", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_011(MpTipoProduto.MEDICAMENTOS, "Vaselina", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_081_012(MpTipoProduto.MEDICAMENTOS, "Redutores de Peso", MpTipoProdutoCategoria.MEDICAMENTOS_081_000),
	MEDICAMENTOS_09_000(MpTipoProduto.MEDICAMENTOS, "Respiratório", null),
	MEDICAMENTOS_09_001(MpTipoProduto.MEDICAMENTOS, "Acessórios para inalador", MpTipoProdutoCategoria.MEDICAMENTOS_09_000),
	MEDICAMENTOS_09_002(MpTipoProduto.MEDICAMENTOS, "Bronco Respiratório", MpTipoProdutoCategoria.MEDICAMENTOS_09_000),
	MEDICAMENTOS_09_003(MpTipoProduto.MEDICAMENTOS, "Dilatador Nasal", MpTipoProdutoCategoria.MEDICAMENTOS_09_000),
	MEDICAMENTOS_10_000(MpTipoProduto.MEDICAMENTOS, "Saúde Feminina", null),
	MEDICAMENTOS_10_001(MpTipoProduto.MEDICAMENTOS, "Anticoncepcionais", MpTipoProdutoCategoria.MEDICAMENTOS_10_000),
	MEDICAMENTOS_10_002(MpTipoProduto.MEDICAMENTOS, "Cólica", MpTipoProdutoCategoria.MEDICAMENTOS_10_000),
	MEDICAMENTOS_10_003(MpTipoProduto.MEDICAMENTOS, "Cremes e óvulos vaginais", MpTipoProdutoCategoria.MEDICAMENTOS_10_000),
	MEDICAMENTOS_10_004(MpTipoProduto.MEDICAMENTOS, "Distúrbios Urinários", MpTipoProdutoCategoria.MEDICAMENTOS_10_000),
	MEDICAMENTOS_10_005(MpTipoProduto.MEDICAMENTOS, "Pílula do Dia Seguinte", MpTipoProdutoCategoria.MEDICAMENTOS_10_000),
	MEDICAMENTOS_11_000(MpTipoProduto.MEDICAMENTOS, "Saúde Masculina", null),
	MEDICAMENTOS_11_001(MpTipoProduto.MEDICAMENTOS, "Disfunção Erétil", MpTipoProdutoCategoria.MEDICAMENTOS_11_000),
	MEDICAMENTOS_11_002(MpTipoProduto.MEDICAMENTOS, "Distúrbios Urinários M.", MpTipoProdutoCategoria.MEDICAMENTOS_11_000),
	MEDICAMENTOS_11_003(MpTipoProduto.MEDICAMENTOS, "Próstata", MpTipoProdutoCategoria.MEDICAMENTOS_11_000),
	MEDICAMENTOS_11_004(MpTipoProduto.MEDICAMENTOS, "Queda de Cabelo", MpTipoProdutoCategoria.MEDICAMENTOS_11_000),
	MEDICAMENTOS_12_000(MpTipoProduto.MEDICAMENTOS, "Sistema Nervoso", null),
	MEDICAMENTOS_12_001(MpTipoProduto.MEDICAMENTOS, "Ansiedade", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_002(MpTipoProduto.MEDICAMENTOS, "Calmantes e Tranquilizantes", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_003(MpTipoProduto.MEDICAMENTOS, "Convulsão e Epilepsia", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_004(MpTipoProduto.MEDICAMENTOS, "Depressão", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_005(MpTipoProduto.MEDICAMENTOS, "Distúrbios Cerebrais", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_006(MpTipoProduto.MEDICAMENTOS, "Esquizofrenia", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_007(MpTipoProduto.MEDICAMENTOS, "Mal de Parkinson", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_008(MpTipoProduto.MEDICAMENTOS, "Neuropsicoestimulante", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_12_009(MpTipoProduto.MEDICAMENTOS, "Outros", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_13_000(MpTipoProduto.MEDICAMENTOS, "Terapia para o Câncer", null),
	MEDICAMENTOS_13_001(MpTipoProduto.MEDICAMENTOS, "Mama", MpTipoProdutoCategoria.MEDICAMENTOS_13_000),
	MEDICAMENTOS_13_002(MpTipoProduto.MEDICAMENTOS, "Próstata.", MpTipoProdutoCategoria.MEDICAMENTOS_13_000),
	MEDICAMENTOS_14_000(MpTipoProduto.MEDICAMENTOS, "Vermes e Parasitas", null),
	MEDICAMENTOS_14_001(MpTipoProduto.MEDICAMENTOS, "Antiparasitários", MpTipoProdutoCategoria.MEDICAMENTOS_14_000),
	MEDICAMENTOS_14_002(MpTipoProduto.MEDICAMENTOS, "Piolhos", MpTipoProdutoCategoria.MEDICAMENTOS_14_000),
	MEDICAMENTOS_14_003(MpTipoProduto.MEDICAMENTOS, "Vermífugos", MpTipoProdutoCategoria.MEDICAMENTOS_14_000),
	MEDICAMENTOS_15_000(MpTipoProduto.MEDICAMENTOS, "Vitaminas e Suplementos", null),
	MEDICAMENTOS_15_001(MpTipoProduto.MEDICAMENTOS, "Anemia", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_002(MpTipoProduto.MEDICAMENTOS, "Betacaroteno", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_003(MpTipoProduto.MEDICAMENTOS, "Chia", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_004(MpTipoProduto.MEDICAMENTOS, "Colágeno e Gelatina", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_005(MpTipoProduto.MEDICAMENTOS, "Complexos Vitamínicos", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_006(MpTipoProduto.MEDICAMENTOS, "Energéticos", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_007(MpTipoProduto.MEDICAMENTOS, "Estimulante de Apetite", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_008(MpTipoProduto.MEDICAMENTOS, "Ginkgo Biloba", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_009(MpTipoProduto.MEDICAMENTOS, "Lecitina de Soja", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_010(MpTipoProduto.MEDICAMENTOS, "Levedo", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_011(MpTipoProduto.MEDICAMENTOS, "Óleo de Alho", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_012(MpTipoProduto.MEDICAMENTOS, "Óleo de Linhaça", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_013(MpTipoProduto.MEDICAMENTOS, "Omega e Óleo de Peixe", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_014(MpTipoProduto.MEDICAMENTOS, "Quitosana", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_015(MpTipoProduto.MEDICAMENTOS, "Vitamina A", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_016(MpTipoProduto.MEDICAMENTOS, "Vitamina B", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_017(MpTipoProduto.MEDICAMENTOS, "Vitamina C", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_018(MpTipoProduto.MEDICAMENTOS, "Vitamina D", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_019(MpTipoProduto.MEDICAMENTOS, "Vitamina E", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_020(MpTipoProduto.MEDICAMENTOS, "Zinco", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	MEDICAMENTOS_15_021(MpTipoProduto.MEDICAMENTOS, "Estimulante Sexual", MpTipoProdutoCategoria.MEDICAMENTOS_12_000),
	GENERICOS_01_000(MpTipoProduto.GENERICOS, "Alergias e Infecções", null),
	GENERICOS_01_001(MpTipoProduto.GENERICOS, "Antialérgicos", MpTipoProdutoCategoria.GENERICOS_01_000),
	GENERICOS_01_002(MpTipoProduto.GENERICOS, "Antibióticos", MpTipoProdutoCategoria.GENERICOS_01_000),
	GENERICOS_01_003(MpTipoProduto.GENERICOS, "Antiviral", MpTipoProdutoCategoria.GENERICOS_01_000),
	GENERICOS_01_004(MpTipoProduto.GENERICOS, "Asma", MpTipoProdutoCategoria.GENERICOS_01_000),
	GENERICOS_01_005(MpTipoProduto.GENERICOS, "Dermatites", MpTipoProdutoCategoria.GENERICOS_01_000),
	GENERICOS_011_000(MpTipoProduto.GENERICOS, "Circulação", null),
	GENERICOS_011_001(MpTipoProduto.GENERICOS, "Antiagregante Plaquetário", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_002(MpTipoProduto.GENERICOS, "Anticoagulante", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_003(MpTipoProduto.GENERICOS, "Cardiovasculares", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_004(MpTipoProduto.GENERICOS, "Coagulação", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_005(MpTipoProduto.GENERICOS, "Trombose", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_006(MpTipoProduto.GENERICOS, "Varizes", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_007(MpTipoProduto.GENERICOS, "Vasodilatador", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_008(MpTipoProduto.GENERICOS, "Hipotensor", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_011_009(MpTipoProduto.GENERICOS, "Colesterol e Triglicerídeos", MpTipoProdutoCategoria.GENERICOS_011_000),
	GENERICOS_02_000(MpTipoProduto.GENERICOS, "Diabetes", null),
	GENERICOS_02_001(MpTipoProduto.GENERICOS, "Hipoglicemiante", MpTipoProdutoCategoria.GENERICOS_02_000),
	GENERICOS_03_000(MpTipoProduto.GENERICOS, "Digestão e Regulador Intestinal", null),
	GENERICOS_03_001(MpTipoProduto.GENERICOS, "Antiácidos", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_03_002(MpTipoProduto.GENERICOS, "Antiespasmódico", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_03_003(MpTipoProduto.GENERICOS, "Antigases", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_03_004(MpTipoProduto.GENERICOS, "Diarreia", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_03_005(MpTipoProduto.GENERICOS, "Hemorroidas", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_03_006(MpTipoProduto.GENERICOS, "Náuseas", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_03_007(MpTipoProduto.GENERICOS, "Úlcera e Gastrite", MpTipoProdutoCategoria.GENERICOS_03_000),
	GENERICOS_031_000(MpTipoProduto.GENERICOS, "Doença dos Ossos", null),
	GENERICOS_031_001(MpTipoProduto.GENERICOS, "Osteoporose", MpTipoProdutoCategoria.GENERICOS_031_000),
	GENERICOS_04_000(MpTipoProduto.GENERICOS, "Dor e Contusão", null),
	GENERICOS_04_001(MpTipoProduto.GENERICOS, "Analgésicos e Antitérmicos", MpTipoProdutoCategoria.GENERICOS_04_000),
	GENERICOS_04_002(MpTipoProduto.GENERICOS, "Anti-inflamatórios e Relaxante Muscular", MpTipoProdutoCategoria.GENERICOS_04_000),
	GENERICOS_04_003(MpTipoProduto.GENERICOS, "Enxaqueca", MpTipoProdutoCategoria.GENERICOS_04_000),
	GENERICOS_041_000(MpTipoProduto.GENERICOS, "Genéricos", null),
	GENERICOS_041_001(MpTipoProduto.GENERICOS, "Colesterol e Triglicerídeos.", MpTipoProdutoCategoria.GENERICOS_041_000),
	GENERICOS_05_000(MpTipoProduto.GENERICOS, "Gripes e Resfriados", null),
	GENERICOS_05_001(MpTipoProduto.GENERICOS, "Antigripais", MpTipoProdutoCategoria.GENERICOS_05_000),
	GENERICOS_05_002(MpTipoProduto.GENERICOS, "Descongestionante Nasal", MpTipoProdutoCategoria.GENERICOS_05_000),
	GENERICOS_05_003(MpTipoProduto.GENERICOS, "Tosse", MpTipoProdutoCategoria.GENERICOS_05_000),
	GENERICOS_051_000(MpTipoProduto.GENERICOS, "Hormônios", null),
	GENERICOS_051_001(MpTipoProduto.GENERICOS, "Antiandrogênico", MpTipoProdutoCategoria.GENERICOS_051_000),
	GENERICOS_051_002(MpTipoProduto.GENERICOS, "Gota", MpTipoProdutoCategoria.GENERICOS_051_000),
	GENERICOS_051_003(MpTipoProduto.GENERICOS, "eposição Hormonal", MpTipoProdutoCategoria.GENERICOS_051_000),
	GENERICOS_051_004(MpTipoProduto.GENERICOS, "Tireóide", MpTipoProdutoCategoria.GENERICOS_051_000),
	GENERICOS_06_000(MpTipoProduto.GENERICOS, "Olhos", null),
	GENERICOS_06_001(MpTipoProduto.GENERICOS, "Alergia e Infecções", MpTipoProdutoCategoria.GENERICOS_06_000),
	GENERICOS_06_002(MpTipoProduto.GENERICOS, "Glaucoma", MpTipoProdutoCategoria.GENERICOS_06_000),
	GENERICOS_061_000(MpTipoProduto.GENERICOS, "Ouvido", null),
	GENERICOS_061_001(MpTipoProduto.GENERICOS, "Analgésico e Anti-inflamatório.", MpTipoProdutoCategoria.GENERICOS_061_000),
	GENERICOS_061_002(MpTipoProduto.GENERICOS, "Antibiótico.", MpTipoProdutoCategoria.GENERICOS_061_000),
	GENERICOS_061_003(MpTipoProduto.GENERICOS, "Cera", MpTipoProdutoCategoria.GENERICOS_061_000),
	GENERICOS_062_000(MpTipoProduto.GENERICOS, "Pare de Fumar", null),
	GENERICOS_062_001(MpTipoProduto.GENERICOS, "Adesivos", MpTipoProdutoCategoria.GENERICOS_062_000),
	GENERICOS_062_002(MpTipoProduto.GENERICOS, "Antitabagismo", MpTipoProdutoCategoria.GENERICOS_062_000),
	GENERICOS_062_003(MpTipoProduto.GENERICOS, "Gomas e Pastilhas", MpTipoProdutoCategoria.GENERICOS_062_000),
	GENERICOS_07_000(MpTipoProduto.GENERICOS, "Pele e Mucosas", null),
	GENERICOS_07_001(MpTipoProduto.GENERICOS, "Acne", MpTipoProdutoCategoria.GENERICOS_07_000),
	GENERICOS_07_002(MpTipoProduto.GENERICOS, "Anestésicos", MpTipoProdutoCategoria.GENERICOS_07_000),
	GENERICOS_07_003(MpTipoProduto.GENERICOS, "Antimicóticos e Fungos", MpTipoProdutoCategoria.GENERICOS_07_000),
	GENERICOS_07_004(MpTipoProduto.GENERICOS, "Cicatrizantes", MpTipoProdutoCategoria.GENERICOS_07_000),
	GENERICOS_07_005(MpTipoProduto.GENERICOS, "Despigmentador", MpTipoProdutoCategoria.GENERICOS_07_000),
	GENERICOS_08_000(MpTipoProduto.GENERICOS, "Pressão Alta", null),
	GENERICOS_08_001(MpTipoProduto.GENERICOS, "Anti-hipertensivo", MpTipoProdutoCategoria.GENERICOS_08_000),
	GENERICOS_08_002(MpTipoProduto.GENERICOS, "Diuréticos", MpTipoProdutoCategoria.GENERICOS_08_000),
	GENERICOS_081_000(MpTipoProduto.GENERICOS, "Primeiros Socorros", null),
	GENERICOS_081_001(MpTipoProduto.GENERICOS, "Curativos", MpTipoProdutoCategoria.GENERICOS_081_000),
	GENERICOS_081_002(MpTipoProduto.GENERICOS, "Redutores de Peso", MpTipoProdutoCategoria.GENERICOS_081_000),
	GENERICOS_09_000(MpTipoProduto.GENERICOS, "Respiratório", null),
	GENERICOS_09_001(MpTipoProduto.GENERICOS, "Bronco Respiratório", MpTipoProdutoCategoria.GENERICOS_09_000),
	GENERICOS_10_000(MpTipoProduto.GENERICOS, "Saúde Feminina", null),
	GENERICOS_10_001(MpTipoProduto.GENERICOS, "Anticoncepcionais", MpTipoProdutoCategoria.GENERICOS_10_000),
	GENERICOS_10_002(MpTipoProduto.GENERICOS, "Cólica", MpTipoProdutoCategoria.GENERICOS_10_000),
	GENERICOS_10_003(MpTipoProduto.GENERICOS, "Cremes e óvulos vaginais", MpTipoProdutoCategoria.GENERICOS_10_000),
	GENERICOS_10_004(MpTipoProduto.GENERICOS, "Distúrbios Urinários", MpTipoProdutoCategoria.GENERICOS_10_000),
	GENERICOS_10_005(MpTipoProduto.GENERICOS, "Pílula do Dia Seguinte", MpTipoProdutoCategoria.GENERICOS_10_000),
	GENERICOS_11_000(MpTipoProduto.GENERICOS, "Saúde Masculina", null),
	GENERICOS_11_001(MpTipoProduto.GENERICOS, "Disfunção Erétil", MpTipoProdutoCategoria.GENERICOS_11_000),
	GENERICOS_11_002(MpTipoProduto.GENERICOS, "Próstata", MpTipoProdutoCategoria.GENERICOS_11_000),
	GENERICOS_11_003(MpTipoProduto.GENERICOS, "Queda de Cabelo", MpTipoProdutoCategoria.GENERICOS_11_000),
	GENERICOS_12_000(MpTipoProduto.GENERICOS, "Sistema Nervoso", null),
	GENERICOS_12_001(MpTipoProduto.GENERICOS, "Ansiedade", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_002(MpTipoProduto.GENERICOS, "Calmantes e Tranquilizantes", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_003(MpTipoProduto.GENERICOS, "Convulsão e Epilepsia", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_004(MpTipoProduto.GENERICOS, "Depressão", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_005(MpTipoProduto.GENERICOS, "Distúrbios Cerebrais", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_006(MpTipoProduto.GENERICOS, "Esquizofrenia", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_007(MpTipoProduto.GENERICOS, "Mal de Parkinson", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_008(MpTipoProduto.GENERICOS, "Neuropsicoestimulante", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_12_009(MpTipoProduto.GENERICOS, "Outros", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_13_000(MpTipoProduto.GENERICOS, "Terapia para o Câncer", null),
	GENERICOS_13_001(MpTipoProduto.GENERICOS, "Mama", MpTipoProdutoCategoria.GENERICOS_13_000),
	GENERICOS_13_002(MpTipoProduto.GENERICOS, "Próstata.", MpTipoProdutoCategoria.GENERICOS_13_000),
	GENERICOS_14_000(MpTipoProduto.GENERICOS, "Vermes e Parasitas", null),
	GENERICOS_14_001(MpTipoProduto.GENERICOS, "Antiparasitários", MpTipoProdutoCategoria.GENERICOS_14_000),
	GENERICOS_14_002(MpTipoProduto.GENERICOS, "Piolhos", MpTipoProdutoCategoria.GENERICOS_14_000),
	GENERICOS_14_003(MpTipoProduto.GENERICOS, "Vermífugos", MpTipoProdutoCategoria.GENERICOS_14_000),
	GENERICOS_15_000(MpTipoProduto.GENERICOS, "Vitaminas e Suplementos", null),
	GENERICOS_15_001(MpTipoProduto.GENERICOS, "Anemia", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_002(MpTipoProduto.GENERICOS, "Betacaroteno", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_003(MpTipoProduto.GENERICOS, "Chia", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_004(MpTipoProduto.GENERICOS, "Colágeno e Gelatina", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_005(MpTipoProduto.GENERICOS, "Complexos Vitamínicos", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_006(MpTipoProduto.GENERICOS, "Energéticos", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_007(MpTipoProduto.GENERICOS, "Estimulante de Apetite", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_008(MpTipoProduto.GENERICOS, "Ginkgo Biloba", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_009(MpTipoProduto.GENERICOS, "Lecitina de Soja", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_010(MpTipoProduto.GENERICOS, "Levedo", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_011(MpTipoProduto.GENERICOS, "Óleo de Alho", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_012(MpTipoProduto.GENERICOS, "Óleo de Linhaça", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_013(MpTipoProduto.GENERICOS, "Omega e Óleo de Peixe", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_014(MpTipoProduto.GENERICOS, "Quitosana", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_015(MpTipoProduto.GENERICOS, "Vitamina A", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_016(MpTipoProduto.GENERICOS, "Vitamina B", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_017(MpTipoProduto.GENERICOS, "Vitamina C", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_018(MpTipoProduto.GENERICOS, "Vitamina D", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_019(MpTipoProduto.GENERICOS, "Vitamina E", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_020(MpTipoProduto.GENERICOS, "Zinco", MpTipoProdutoCategoria.GENERICOS_12_000),
	GENERICOS_15_021(MpTipoProduto.GENERICOS, "Estimulante Sexual", MpTipoProdutoCategoria.GENERICOS_12_000),
	DERMOCOSMETICOS_01_000(MpTipoProduto.DERMOCOSMETICOS, "Cabelo/Capilar", null),
	DERMOCOSMETICOS_01_001(MpTipoProduto.DERMOCOSMETICOS, "Antiqueda", MpTipoProdutoCategoria.DERMOCOSMETICOS_01_000),
	DERMOCOSMETICOS_01_002(MpTipoProduto.DERMOCOSMETICOS, "Condicionador", MpTipoProdutoCategoria.DERMOCOSMETICOS_01_000),
	DERMOCOSMETICOS_01_003(MpTipoProduto.DERMOCOSMETICOS, "Shampoo", MpTipoProdutoCategoria.DERMOCOSMETICOS_01_000),
	DERMOCOSMETICOS_01_004(MpTipoProduto.DERMOCOSMETICOS, "Tratamento", MpTipoProdutoCategoria.DERMOCOSMETICOS_01_000),
	DERMOCOSMETICOS_02_000(MpTipoProduto.DERMOCOSMETICOS, "Corpo/Corporal", null),
	DERMOCOSMETICOS_02_001(MpTipoProduto.DERMOCOSMETICOS, "Antiestrias", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_02_002(MpTipoProduto.DERMOCOSMETICOS, "Auto Bronzeador", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_02_003(MpTipoProduto.DERMOCOSMETICOS, "Desodorante Aerosol", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_02_004(MpTipoProduto.DERMOCOSMETICOS, "Desodorante Roll On", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_02_005(MpTipoProduto.DERMOCOSMETICOS, "Hidratante Corporal", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_02_006(MpTipoProduto.DERMOCOSMETICOS, "Protetor Solar Corporal", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_02_007(MpTipoProduto.DERMOCOSMETICOS, "Cicatrizante", MpTipoProdutoCategoria.DERMOCOSMETICOS_02_000),
	DERMOCOSMETICOS_021_000(MpTipoProduto.DERMOCOSMETICOS, "Nutricosméticos", null),
	DERMOCOSMETICOS_021_001(MpTipoProduto.DERMOCOSMETICOS, "Anticelulite e Firmador", MpTipoProdutoCategoria.DERMOCOSMETICOS_021_000),
	DERMOCOSMETICOS_021_002(MpTipoProduto.DERMOCOSMETICOS, "Antioxidante", MpTipoProdutoCategoria.DERMOCOSMETICOS_021_000),
	DERMOCOSMETICOS_021_003(MpTipoProduto.DERMOCOSMETICOS, "Fortalecedor de Cabelos e Unhas", MpTipoProdutoCategoria.DERMOCOSMETICOS_021_000),
	DERMOCOSMETICOS_021_004(MpTipoProduto.DERMOCOSMETICOS, "Redutor de Medidas", MpTipoProdutoCategoria.DERMOCOSMETICOS_021_000),
	DERMOCOSMETICOS_021_005(MpTipoProduto.DERMOCOSMETICOS, "Solar", MpTipoProdutoCategoria.DERMOCOSMETICOS_021_000),
	DERMOCOSMETICOS_03_000(MpTipoProduto.DERMOCOSMETICOS, "Olhos", null),
	DERMOCOSMETICOS_04_000(MpTipoProduto.DERMOCOSMETICOS, "Rosto", null),
	DERMOCOSMETICOS_04_001(MpTipoProduto.DERMOCOSMETICOS, "Antiacne", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_002(MpTipoProduto.DERMOCOSMETICOS, "Anti-idade", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_003(MpTipoProduto.DERMOCOSMETICOS, "Antirrugas", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_004(MpTipoProduto.DERMOCOSMETICOS, "Despigmentador", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_005(MpTipoProduto.DERMOCOSMETICOS, "Gel e Espuma de Limpeza", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_006(MpTipoProduto.DERMOCOSMETICOS, "Hidratante", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_007(MpTipoProduto.DERMOCOSMETICOS, "Protetor Labial", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_008(MpTipoProduto.DERMOCOSMETICOS, "Protetor Solar Facial", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_009(MpTipoProduto.DERMOCOSMETICOS, "Sabonete em Barra", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	DERMOCOSMETICOS_04_010(MpTipoProduto.DERMOCOSMETICOS, "Sabonete Líquido", MpTipoProdutoCategoria.DERMOCOSMETICOS_04_000),
	HIGIENE_01_000(MpTipoProduto.HIGIENE, "Absorventes", null),
	HIGIENE_02_000(MpTipoProduto.HIGIENE, "Barba", null),
	HIGIENE_02_001(MpTipoProduto.HIGIENE, "Aparelho De Barbear", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_002(MpTipoProduto.HIGIENE, "Aparelho de Barbear Descartável", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_003(MpTipoProduto.HIGIENE, "Barbeador Elétrico", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_004(MpTipoProduto.HIGIENE, "Creme de Barbear", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_005(MpTipoProduto.HIGIENE, "Espuma de Barbear", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_006(MpTipoProduto.HIGIENE, "Gel de Barbear", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_007(MpTipoProduto.HIGIENE, "Pós-barba", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_008(MpTipoProduto.HIGIENE, "Refil para Barbeador", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_02_009(MpTipoProduto.HIGIENE, "Condicionador.", MpTipoProdutoCategoria.HIGIENE_02_000),
	HIGIENE_021_000(MpTipoProduto.HIGIENE, "Geriátrico", null),
	HIGIENE_021_001(MpTipoProduto.HIGIENE, "Absorvente Geriátrico", MpTipoProdutoCategoria.HIGIENE_021_000),
	HIGIENE_021_002(MpTipoProduto.HIGIENE, "Fralda Geriátrica", MpTipoProdutoCategoria.HIGIENE_021_000),
	HIGIENE_021_003(MpTipoProduto.HIGIENE, "Lenços Umedecidos", MpTipoProdutoCategoria.HIGIENE_021_000),
	HIGIENE_021_004(MpTipoProduto.HIGIENE, "Papagaio", MpTipoProdutoCategoria.HIGIENE_021_000),
	HIGIENE_021_005(MpTipoProduto.HIGIENE, "Protetor de Colchão", MpTipoProdutoCategoria.HIGIENE_021_000),
	HIGIENE_021_006(MpTipoProduto.HIGIENE, "Roupa Íntima", MpTipoProdutoCategoria.HIGIENE_021_000),
	HIGIENE_03_000(MpTipoProduto.HIGIENE, "Higiene Oral", null),
	HIGIENE_03_001(MpTipoProduto.HIGIENE, "Antisséptico Bucal", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_002(MpTipoProduto.HIGIENE, "Branqueador Dental", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_003(MpTipoProduto.HIGIENE, "Creme e Gel Dental", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_004(MpTipoProduto.HIGIENE, "Escova Dental", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_005(MpTipoProduto.HIGIENE, "Fios e Fitas Dentais", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_006(MpTipoProduto.HIGIENE, "Fixador e Limpeza de Próteses", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_007(MpTipoProduto.HIGIENE, "Limpa Língua", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_008(MpTipoProduto.HIGIENE, "Outros", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_03_009(MpTipoProduto.HIGIENE, "Porta Escova", MpTipoProdutoCategoria.HIGIENE_03_000),
	HIGIENE_04_000(MpTipoProduto.HIGIENE, "Higiene Pessoal", null),
	HIGIENE_04_001(MpTipoProduto.HIGIENE, "Acessórios", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_04_002(MpTipoProduto.HIGIENE, "Algodão e Hastes Flexíveis", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_04_003(MpTipoProduto.HIGIENE, "Gel Antisséptico", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_04_004(MpTipoProduto.HIGIENE, "Higiene Íntima", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_04_005(MpTipoProduto.HIGIENE, "Lenços de Papel", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_04_006(MpTipoProduto.HIGIENE, "Papel Higiênico ", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_04_007(MpTipoProduto.HIGIENE, "Sabonetes Íntimos", MpTipoProdutoCategoria.HIGIENE_04_000),
	HIGIENE_05_000(MpTipoProduto.HIGIENE, "Higiene Corporal", null),
	HIGIENE_05_001(MpTipoProduto.HIGIENE, "Esponja para Banho", MpTipoProdutoCategoria.HIGIENE_05_000),
	HIGIENE_05_002(MpTipoProduto.HIGIENE, "Sabonetes", MpTipoProdutoCategoria.HIGIENE_05_000),
	HIGIENE_05_003(MpTipoProduto.HIGIENE, "Sabonetes Especiais", MpTipoProdutoCategoria.HIGIENE_05_000),
	HIGIENE_05_004(MpTipoProduto.HIGIENE, "Sabonetes Líquidos", MpTipoProdutoCategoria.HIGIENE_05_000),
	HIGIENE_06_000(MpTipoProduto.HIGIENE, "Shampoo", null),
	HIGIENE_06_001(MpTipoProduto.HIGIENE, "Anticaspa", MpTipoProdutoCategoria.HIGIENE_06_000),
	HIGIENE_06_002(MpTipoProduto.HIGIENE, "Anticoceira", MpTipoProdutoCategoria.HIGIENE_06_000),
	HIGIENE_06_003(MpTipoProduto.HIGIENE, "Antiqueda", MpTipoProdutoCategoria.HIGIENE_06_000),
	HIGIENE_06_004(MpTipoProduto.HIGIENE, "Antirresíduos", MpTipoProdutoCategoria.HIGIENE_06_000),
	HIGIENE_07_000(MpTipoProduto.HIGIENE, "Condicionador", null),
	HIGIENE_07_001(MpTipoProduto.HIGIENE, "Anticaspa.", MpTipoProdutoCategoria.HIGIENE_07_000),
	HIGIENE_07_002(MpTipoProduto.HIGIENE, "Anticoceira.", MpTipoProdutoCategoria.HIGIENE_07_000),
	HIGIENE_07_003(MpTipoProduto.HIGIENE, "Antiqueda.", MpTipoProdutoCategoria.HIGIENE_07_000),
	HIGIENE_07_004(MpTipoProduto.HIGIENE, "Antirresíduos.", MpTipoProdutoCategoria.HIGIENE_07_000),
	HIGIENE_08_000(MpTipoProduto.HIGIENE, "Kits Especiais", null),
	HIGIENE_08_001(MpTipoProduto.HIGIENE, "Shampoo e Condicionador", MpTipoProdutoCategoria.HIGIENE_08_000),
	HIGIENE_08_002(MpTipoProduto.HIGIENE, "Sabonetes Especiais.", MpTipoProdutoCategoria.HIGIENE_08_000),
	HIGIENE_09_000(MpTipoProduto.HIGIENE, "Repelentes", null),
	HIGIENE_09_001(MpTipoProduto.HIGIENE, "Acessórios.", MpTipoProdutoCategoria.HIGIENE_09_000),
	HIGIENE_09_002(MpTipoProduto.HIGIENE, "Aerosol", MpTipoProdutoCategoria.HIGIENE_09_000),
	HIGIENE_09_003(MpTipoProduto.HIGIENE, "Loção", MpTipoProdutoCategoria.HIGIENE_09_000),
	HIGIENE_09_004(MpTipoProduto.HIGIENE, "Spray", MpTipoProdutoCategoria.HIGIENE_09_000),
	HIGIENE_09_005(MpTipoProduto.HIGIENE, "Shampoo...", MpTipoProdutoCategoria.HIGIENE_09_000),
	HIGIENE_09_006(MpTipoProduto.HIGIENE, "Shampoo e Condicionador...", MpTipoProdutoCategoria.HIGIENE_09_000),
	HIGIENE_10_000(MpTipoProduto.HIGIENE, "Pés", null),
	HIGIENE_10_001(MpTipoProduto.HIGIENE, "Acessórios..", MpTipoProdutoCategoria.HIGIENE_10_000),
	HIGIENE_10_002(MpTipoProduto.HIGIENE, "Desodorante.", MpTipoProdutoCategoria.HIGIENE_10_000),
	HIGIENE_10_003(MpTipoProduto.HIGIENE, "Esfoliante.", MpTipoProdutoCategoria.HIGIENE_10_000),
	HIGIENE_11_000(MpTipoProduto.HIGIENE, "Utilidade para o Lar", null),
	HIGIENE_11_001(MpTipoProduto.HIGIENE, "Higiene de Ambiente", MpTipoProdutoCategoria.HIGIENE_11_000),
	HIGIENE_12_000(MpTipoProduto.HIGIENE, "Vida Sexual", null),
	HIGIENE_12_001(MpTipoProduto.HIGIENE, "Lubrificantes", MpTipoProdutoCategoria.HIGIENE_12_000),
	HIGIENE_12_002(MpTipoProduto.HIGIENE, "Preservativos", MpTipoProdutoCategoria.HIGIENE_12_000),
	HIGIENE_12_003(MpTipoProduto.HIGIENE, "Preservativos Femininos", MpTipoProdutoCategoria.HIGIENE_12_000),
	BEBE_MAMAE_01_000(MpTipoProduto.BEBE_MAMAE, "Acessórios Infantis", null),
	BEBE_MAMAE_01_001(MpTipoProduto.BEBE_MAMAE, "Aspirador Nasal", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_002(MpTipoProduto.BEBE_MAMAE, "Babadores", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_003(MpTipoProduto.BEBE_MAMAE, "Bicos de Mamadeira", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_004(MpTipoProduto.BEBE_MAMAE, "Chupetas", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_005(MpTipoProduto.BEBE_MAMAE, "Copos", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_006(MpTipoProduto.BEBE_MAMAE, "Escovas e Pentes", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_007(MpTipoProduto.BEBE_MAMAE, "Limpador de Mamadeira", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_008(MpTipoProduto.BEBE_MAMAE, "Mamadeiras", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_009(MpTipoProduto.BEBE_MAMAE, "Mordedores", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_010(MpTipoProduto.BEBE_MAMAE, "Pratos e Dosador de Leite", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_011(MpTipoProduto.BEBE_MAMAE, "Prendedores de Chupeta", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_012(MpTipoProduto.BEBE_MAMAE, "Talheres", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_01_013(MpTipoProduto.BEBE_MAMAE, "Tesoura e Cortador de Unha", MpTipoProdutoCategoria.BEBE_MAMAE_01_000),
	BEBE_MAMAE_02_000(MpTipoProduto.BEBE_MAMAE, "Alimentos Infantis", null),
	BEBE_MAMAE_02_001(MpTipoProduto.BEBE_MAMAE, "Cereais Infantis", MpTipoProdutoCategoria.BEBE_MAMAE_02_000),
	BEBE_MAMAE_02_002(MpTipoProduto.BEBE_MAMAE, "Complemento Alimentar Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_02_000),
	BEBE_MAMAE_02_003(MpTipoProduto.BEBE_MAMAE, "Leites e Fórmulas Infantis", MpTipoProdutoCategoria.BEBE_MAMAE_02_000),
	BEBE_MAMAE_02_004(MpTipoProduto.BEBE_MAMAE, "Papinhas", MpTipoProdutoCategoria.BEBE_MAMAE_02_000),
	BEBE_MAMAE_03_000(MpTipoProduto.BEBE_MAMAE, "Corpo e Banho", null),
	BEBE_MAMAE_03_001(MpTipoProduto.BEBE_MAMAE, "Colônias Infantis", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_002(MpTipoProduto.BEBE_MAMAE, "Condicionador Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_003(MpTipoProduto.BEBE_MAMAE, "Esponjas", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_004(MpTipoProduto.BEBE_MAMAE, "Fixadores e Modeladores", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_005(MpTipoProduto.BEBE_MAMAE, "Hidratante para o Corpo Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_006(MpTipoProduto.BEBE_MAMAE, "Hidratante para o Rosto Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_007(MpTipoProduto.BEBE_MAMAE, "Limpeza Corpo e Face", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_008(MpTipoProduto.BEBE_MAMAE, "Massagem Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_009(MpTipoProduto.BEBE_MAMAE, "Protetor Solar Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_010(MpTipoProduto.BEBE_MAMAE, "Sabonete Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_011(MpTipoProduto.BEBE_MAMAE, "Sabonete Líquido Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_012(MpTipoProduto.BEBE_MAMAE, "Shampoo Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_013(MpTipoProduto.BEBE_MAMAE, "Talco Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_03_014(MpTipoProduto.BEBE_MAMAE, "Repelente Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_03_000),
	BEBE_MAMAE_04_000(MpTipoProduto.BEBE_MAMAE, "Cuidado Bucal Infantil", null),
	BEBE_MAMAE_04_001(MpTipoProduto.BEBE_MAMAE, "Creme Dental", MpTipoProdutoCategoria.BEBE_MAMAE_04_000),
	BEBE_MAMAE_04_002(MpTipoProduto.BEBE_MAMAE, "Escova Dental", MpTipoProdutoCategoria.BEBE_MAMAE_04_000),
	BEBE_MAMAE_04_003(MpTipoProduto.BEBE_MAMAE, "Higiene Bucal Bebê", MpTipoProdutoCategoria.BEBE_MAMAE_04_000),
	BEBE_MAMAE_04_004(MpTipoProduto.BEBE_MAMAE, "Solução Bucal Infantil", MpTipoProdutoCategoria.BEBE_MAMAE_04_000),
	BEBE_MAMAE_05_000(MpTipoProduto.BEBE_MAMAE, "Fraldas", null),
	BEBE_MAMAE_05_001(MpTipoProduto.BEBE_MAMAE, "Fralda para Piscina", MpTipoProdutoCategoria.BEBE_MAMAE_05_000),
	BEBE_MAMAE_05_002(MpTipoProduto.BEBE_MAMAE, "Uso diário", MpTipoProdutoCategoria.BEBE_MAMAE_05_000),
	BEBE_MAMAE_06_000(MpTipoProduto.BEBE_MAMAE, "Para a troca do bebê", null),
	BEBE_MAMAE_06_001(MpTipoProduto.BEBE_MAMAE, "Assaduras do Bebê", MpTipoProdutoCategoria.BEBE_MAMAE_06_000),
	BEBE_MAMAE_06_002(MpTipoProduto.BEBE_MAMAE, "Fitas Adesivas", MpTipoProdutoCategoria.BEBE_MAMAE_06_000),
	BEBE_MAMAE_06_003(MpTipoProduto.BEBE_MAMAE, "Lenços Umedecidos", MpTipoProdutoCategoria.BEBE_MAMAE_06_000),
	BEBE_MAMAE_07_000(MpTipoProduto.BEBE_MAMAE, "Cuidado com a mãe", null),
	BEBE_MAMAE_07_001(MpTipoProduto.BEBE_MAMAE, "Absorvente para seios", MpTipoProdutoCategoria.BEBE_MAMAE_07_000),
	BEBE_MAMAE_07_002(MpTipoProduto.BEBE_MAMAE, "Amamentação", MpTipoProdutoCategoria.BEBE_MAMAE_07_000),
	BEBE_MAMAE_07_003(MpTipoProduto.BEBE_MAMAE, "Meias Elásticas", MpTipoProdutoCategoria.BEBE_MAMAE_07_000),
	BEBE_MAMAE_07_004(MpTipoProduto.BEBE_MAMAE, "Tratamento Corpo Mamãe", MpTipoProdutoCategoria.BEBE_MAMAE_07_000),
	BEBE_MAMAE_08_000(MpTipoProduto.BEBE_MAMAE, "Kits e Presentes", null),
	BEBE_MAMAE_09_000(MpTipoProduto.BEBE_MAMAE, "Saúde do Bebê", null),
	BEBE_MAMAE_09_001(MpTipoProduto.BEBE_MAMAE, "Primeira Dentição", MpTipoProdutoCategoria.BEBE_MAMAE_09_000),
	ORTOPEDIA_ACESSORIOS_01_000(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Acessórios", null),
	ORTOPEDIA_ACESSORIOS_01_001(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Bolinha de fisioterapia", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_01_000),
	ORTOPEDIA_ACESSORIOS_01_002(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Bolsa Térmica", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_01_000),
	ORTOPEDIA_ACESSORIOS_01_003(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Faixa Abdominal e Torácica", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_01_000),
	ORTOPEDIA_ACESSORIOS_01_004(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Suspensório Escrotal", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_01_000),
	ORTOPEDIA_ACESSORIOS_02_000(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Cabeça", null),
	ORTOPEDIA_ACESSORIOS_02_001(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Máscara", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_02_000),
	ORTOPEDIA_ACESSORIOS_02_002(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Protetor de Ouvido", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_02_000),
	ORTOPEDIA_ACESSORIOS_03_000(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Mãos e Braços", null),
	ORTOPEDIA_ACESSORIOS_03_001(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Luvas", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_03_000),
	ORTOPEDIA_ACESSORIOS_03_002(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Munhequeiras", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_03_000),
	ORTOPEDIA_ACESSORIOS_03_003(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Tala para Tendinite", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_03_000),
	ORTOPEDIA_ACESSORIOS_04_000(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Pés e Pernas", null),
	ORTOPEDIA_ACESSORIOS_04_001(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Calcanheira", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_04_000),
	ORTOPEDIA_ACESSORIOS_04_002(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Meias", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_04_000),
	ORTOPEDIA_ACESSORIOS_04_003(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Palmilha", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_04_000),
	ORTOPEDIA_ACESSORIOS_04_004(MpTipoProduto.ORTOPEDIA_ACESSORIOS, "Tornozeleira e Joelheira", MpTipoProdutoCategoria.ORTOPEDIA_ACESSORIOS_04_000),
	ESTETETICA_01_000(MpTipoProduto.ESTETETICA, "Acessórios", null),
	ESTETETICA_01_001(MpTipoProduto.ESTETETICA, "Acessórios para Cabelos", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_002(MpTipoProduto.ESTETETICA, "Chapinha", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_003(MpTipoProduto.ESTETETICA, "Cortador de Cabelos", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_004(MpTipoProduto.ESTETETICA, "Escovas e Pentes", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_005(MpTipoProduto.ESTETETICA, "Grampos para Cabelos", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_006(MpTipoProduto.ESTETETICA, "Modelador de Seios", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_007(MpTipoProduto.ESTETETICA, "Outros", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_008(MpTipoProduto.ESTETETICA, "Pilhas e Baterias", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_01_009(MpTipoProduto.ESTETETICA, "Secador de Cabelo", MpTipoProdutoCategoria.ESTETETICA_01_000),
	ESTETETICA_02_000(MpTipoProduto.ESTETETICA, "Cuidados com a Pele", null),
	ESTETETICA_02_001(MpTipoProduto.ESTETETICA, "Antiacne", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_002(MpTipoProduto.ESTETETICA, "Anticravos", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_003(MpTipoProduto.ESTETETICA, "Creme Antirrugas", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_004(MpTipoProduto.ESTETETICA, "Creme Facial", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_005(MpTipoProduto.ESTETETICA, "Creme para Mãoss", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_006(MpTipoProduto.ESTETETICA, "Creme para Pernas", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_007(MpTipoProduto.ESTETETICA, "Creme para Pés", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_008(MpTipoProduto.ESTETETICA, "Hidratante Corporal", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_009(MpTipoProduto.ESTETETICA, "Limpeza de pele", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_010(MpTipoProduto.ESTETETICA, "Óleo de Amêndoas", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_011(MpTipoProduto.ESTETETICA, "Protetor Labial", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_02_012(MpTipoProduto.ESTETETICA, "Talco", MpTipoProdutoCategoria.ESTETETICA_02_000),
	ESTETETICA_03_000(MpTipoProduto.ESTETETICA, "Depilação/Estética Masculina", null),
	ESTETETICA_03_001(MpTipoProduto.ESTETETICA, "Aparador de Pelos", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_002(MpTipoProduto.ESTETETICA, "Anticravos.", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_003(MpTipoProduto.ESTETETICA, "Aparelho Depilatório", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_004(MpTipoProduto.ESTETETICA, "Carga para depilador", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_005(MpTipoProduto.ESTETETICA, "Creme Depilatório", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_006(MpTipoProduto.ESTETETICA, "Depilador Elétrico", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_007(MpTipoProduto.ESTETETICA, "Folhas para Depilação", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_008(MpTipoProduto.ESTETETICA, "Removedor Pós-depilação", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_03_009(MpTipoProduto.ESTETETICA, "Sobrancelhas", MpTipoProdutoCategoria.ESTETETICA_03_000),
	ESTETETICA_04_000(MpTipoProduto.ESTETETICA, "Finalização e Tratamento", null),
	ESTETETICA_04_001(MpTipoProduto.ESTETETICA, "Ampola de Tratamento", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_002(MpTipoProduto.ESTETETICA, "Creme para Pentear", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_003(MpTipoProduto.ESTETETICA, "Gel Fixador", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_004(MpTipoProduto.ESTETETICA, "Keratina Líquida", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_005(MpTipoProduto.ESTETETICA, "Máscara de Tratamento", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_006(MpTipoProduto.ESTETETICA, "Mousse", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_007(MpTipoProduto.ESTETETICA, "Óleo e loção", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_008(MpTipoProduto.ESTETETICA, "Pomada Modeladora", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_009(MpTipoProduto.ESTETETICA, "Reparador de Pontas", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_010(MpTipoProduto.ESTETETICA, "Spray e Fluidos para Cabelos", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_04_011(MpTipoProduto.ESTETETICA, "Vitaminas", MpTipoProdutoCategoria.ESTETETICA_04_000),
	ESTETETICA_05_000(MpTipoProduto.ESTETETICA, "Finalização e Tratamento Capilar/Tintura", null),
	ESTETETICA_06_000(MpTipoProduto.ESTETETICA, "Kits Especiais", null),
	ESTETETICA_07_000(MpTipoProduto.ESTETETICA, "Proteção Solar/Bronzeamento", null),
	ESTETETICA_07_001(MpTipoProduto.ESTETETICA, "Bronzeador", MpTipoProdutoCategoria.ESTETETICA_07_000),
	ESTETETICA_07_002(MpTipoProduto.ESTETETICA, "Pós Sol", MpTipoProdutoCategoria.ESTETETICA_07_000),
	ESTETETICA_07_003(MpTipoProduto.ESTETETICA, "Protetor", MpTipoProdutoCategoria.ESTETETICA_07_000),
	ESTETETICA_08_000(MpTipoProduto.ESTETETICA, "Tintura e Tratamento", null),
	ESTETETICA_08_001(MpTipoProduto.ESTETETICA, "Alisantes e Relaxamentos", MpTipoProdutoCategoria.ESTETETICA_08_000),
	ESTETETICA_08_002(MpTipoProduto.ESTETETICA, "Descolorante", MpTipoProdutoCategoria.ESTETETICA_08_000),
	ESTETETICA_08_004(MpTipoProduto.ESTETETICA, "Tintura", MpTipoProdutoCategoria.ESTETETICA_08_000),
	ESTETETICA_09_000(MpTipoProduto.ESTETETICA, "Unhas", null),
	ESTETETICA_09_001(MpTipoProduto.ESTETETICA, "Acessórios.", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_002(MpTipoProduto.ESTETETICA, "Alicate e Cortador", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_003(MpTipoProduto.ESTETETICA, "Base", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_004(MpTipoProduto.ESTETETICA, "Esmaltes", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_005(MpTipoProduto.ESTETETICA, "Fixador e Secante", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_006(MpTipoProduto.ESTETETICA, "Removedor de Esmalte", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_007(MpTipoProduto.ESTETETICA, "Tesoura e Lixa", MpTipoProdutoCategoria.ESTETETICA_09_000),
	ESTETETICA_09_008(MpTipoProduto.ESTETETICA, "Unhas Postiças", MpTipoProdutoCategoria.ESTETETICA_09_000),
	NUTRICAO_ALIMENTOS_01_000(MpTipoProduto.NUTRICAO_ALIMENTOS, "Alimentos", null),
	NUTRICAO_ALIMENTOS_01_001(MpTipoProduto.NUTRICAO_ALIMENTOS, "Adoçante", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_002(MpTipoProduto.NUTRICAO_ALIMENTOS, "Balas", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_003(MpTipoProduto.NUTRICAO_ALIMENTOS, "BArra de Cereal", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_004(MpTipoProduto.NUTRICAO_ALIMENTOS, "Chicletes", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_005(MpTipoProduto.NUTRICAO_ALIMENTOS, "Chocolates", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_006(MpTipoProduto.NUTRICAO_ALIMENTOS, "Complemento Alimentar", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_007(MpTipoProduto.NUTRICAO_ALIMENTOS, "Cookies", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_008(MpTipoProduto.NUTRICAO_ALIMENTOS, "Frutas Secas", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_009(MpTipoProduto.NUTRICAO_ALIMENTOS, "Geléias", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_010(MpTipoProduto.NUTRICAO_ALIMENTOS, "Granola", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_01_011(MpTipoProduto.NUTRICAO_ALIMENTOS, "Sal", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_01_000),
	NUTRICAO_ALIMENTOS_02_000(MpTipoProduto.NUTRICAO_ALIMENTOS, "Bebidas", null),
	NUTRICAO_ALIMENTOS_02_001(MpTipoProduto.NUTRICAO_ALIMENTOS, "Achocolatado", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_02_002(MpTipoProduto.NUTRICAO_ALIMENTOS, "Água", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_02_003(MpTipoProduto.NUTRICAO_ALIMENTOS, "Água de Côco", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_02_004(MpTipoProduto.NUTRICAO_ALIMENTOS, "Chá", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_02_005(MpTipoProduto.NUTRICAO_ALIMENTOS, "Energético", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_02_006(MpTipoProduto.NUTRICAO_ALIMENTOS, "Isôtonico", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_02_007(MpTipoProduto.NUTRICAO_ALIMENTOS, "Suco", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_02_000),
	NUTRICAO_ALIMENTOS_03_000(MpTipoProduto.NUTRICAO_ALIMENTOS, "Nutrição Infantil", null),
	NUTRICAO_ALIMENTOS_04_000(MpTipoProduto.NUTRICAO_ALIMENTOS, "Emagrecedores", null),
	NUTRICAO_ALIMENTOS_04_001(MpTipoProduto.NUTRICAO_ALIMENTOS, "Cápsulas e Tabletes", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_04_000),
	NUTRICAO_ALIMENTOS_04_002(MpTipoProduto.NUTRICAO_ALIMENTOS, "Naturais", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_04_000),
	NUTRICAO_ALIMENTOS_04_003(MpTipoProduto.NUTRICAO_ALIMENTOS, "Shake", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_04_000),
	NUTRICAO_ALIMENTOS_05_000(MpTipoProduto.NUTRICAO_ALIMENTOS, "Nutrição Esportiva", null),
	NUTRICAO_ALIMENTOS_05_001(MpTipoProduto.NUTRICAO_ALIMENTOS, "Energético.", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_05_000),
	NUTRICAO_ALIMENTOS_05_002(MpTipoProduto.NUTRICAO_ALIMENTOS, "Massa Muscular", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_05_000),
	NUTRICAO_ALIMENTOS_05_003(MpTipoProduto.NUTRICAO_ALIMENTOS, "Suplemento Alimentar", MpTipoProdutoCategoria.NUTRICAO_ALIMENTOS_05_000),
	PERFUMARIA_01_000(MpTipoProduto.PERFUMARIA, "Colônias", null),
	PERFUMARIA_02_000(MpTipoProduto.PERFUMARIA, "Desodorante Aerosol", null),
	PERFUMARIA_03_000(MpTipoProduto.PERFUMARIA, "Desodorante Creme e Roll-on", null),
	PERFUMARIA_04_000(MpTipoProduto.PERFUMARIA, "Desodorante Spray", null),
	PERFUMARIA_05_000(MpTipoProduto.PERFUMARIA, "Perfumes", null),
	PERFUMARIA_06_000(MpTipoProduto.PERFUMARIA, "Perfume Ambiente", null),
	PERFUMARIA_07_000(MpTipoProduto.PERFUMARIA, "Kits Especias", null),
	MAQUIAGEM_01_000(MpTipoProduto.MAQUIAGEM, "Lábios", null),
	MAQUIAGEM_01_001(MpTipoProduto.MAQUIAGEM, "Batom", MpTipoProdutoCategoria.MAQUIAGEM_01_000),
	MAQUIAGEM_01_002(MpTipoProduto.MAQUIAGEM, "Batom hidratante", MpTipoProdutoCategoria.MAQUIAGEM_01_000),
	MAQUIAGEM_01_003(MpTipoProduto.MAQUIAGEM, "Brilho Labial", MpTipoProdutoCategoria.MAQUIAGEM_01_000),
	MAQUIAGEM_01_004(MpTipoProduto.MAQUIAGEM, "Lápis", MpTipoProdutoCategoria.MAQUIAGEM_01_000),
	MAQUIAGEM_02_000(MpTipoProduto.MAQUIAGEM, "Olhos", null),
	MAQUIAGEM_02_001(MpTipoProduto.MAQUIAGEM, "Cílios Postiços", MpTipoProdutoCategoria.MAQUIAGEM_02_000),
	MAQUIAGEM_02_002(MpTipoProduto.MAQUIAGEM, "Delineador", MpTipoProdutoCategoria.MAQUIAGEM_02_000),
	MAQUIAGEM_02_003(MpTipoProduto.MAQUIAGEM, "Demaquilante", MpTipoProdutoCategoria.MAQUIAGEM_02_000),
	MAQUIAGEM_02_004(MpTipoProduto.MAQUIAGEM, "Lápis de Olho", MpTipoProdutoCategoria.MAQUIAGEM_02_000),
	MAQUIAGEM_02_005(MpTipoProduto.MAQUIAGEM, "Lápis de Sobrancelha", MpTipoProdutoCategoria.MAQUIAGEM_02_000),
	MAQUIAGEM_02_006(MpTipoProduto.MAQUIAGEM, "Máscara de Cílios", MpTipoProdutoCategoria.MAQUIAGEM_02_000),
	MAQUIAGEM_03_000(MpTipoProduto.MAQUIAGEM, "Rostos", null),
	MAQUIAGEM_03_001(MpTipoProduto.MAQUIAGEM, "Base", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_002(MpTipoProduto.MAQUIAGEM, "Blush", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_003(MpTipoProduto.MAQUIAGEM, "Corretivo", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_004(MpTipoProduto.MAQUIAGEM, "Demaquilante.", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_005(MpTipoProduto.MAQUIAGEM, "Kits Especiais", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_006(MpTipoProduto.MAQUIAGEM, "Pó Facial", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_007(MpTipoProduto.MAQUIAGEM, "Pré-Maquiagem", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_03_008(MpTipoProduto.MAQUIAGEM, "Sombra", MpTipoProdutoCategoria.MAQUIAGEM_03_000),
	MAQUIAGEM_04_000(MpTipoProduto.MAQUIAGEM, "Unhas", null),
	MAQUIAGEM_05_000(MpTipoProduto.MAQUIAGEM, "Kits Especiais.", null),
	TESTES_APARELHOS_01_000(MpTipoProduto.TESTES_APARELHOS, "Acessórios", null),
	TESTES_APARELHOS_02_000(MpTipoProduto.TESTES_APARELHOS, "Testes e Aparelhos", null),
	TESTES_APARELHOS_02_001(MpTipoProduto.TESTES_APARELHOS, "Aparelho de Pressão", MpTipoProdutoCategoria.TESTES_APARELHOS_01_000),
	TESTES_APARELHOS_02_002(MpTipoProduto.TESTES_APARELHOS, "Balança", MpTipoProdutoCategoria.TESTES_APARELHOS_01_000),
	TESTES_APARELHOS_03_000(MpTipoProduto.TESTES_APARELHOS, "Diabetes", null),
	TESTES_APARELHOS_03_001(MpTipoProduto.TESTES_APARELHOS, "Agulhas e Seringas", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_002(MpTipoProduto.TESTES_APARELHOS, "Aparelhos e Medidores", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_003(MpTipoProduto.TESTES_APARELHOS, "Lancetas e Tiras", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_004(MpTipoProduto.TESTES_APARELHOS, "Inalador, Purificador e Acessórios", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_005(MpTipoProduto.TESTES_APARELHOS, "Massageador", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_006(MpTipoProduto.TESTES_APARELHOS, "Termômetro", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_007(MpTipoProduto.TESTES_APARELHOS, "Teste de Gravidez", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_008(MpTipoProduto.TESTES_APARELHOS, "Bolsa Para Colostomia", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_03_009(MpTipoProduto.TESTES_APARELHOS, "Coletor de Fezes e Urina", MpTipoProdutoCategoria.TESTES_APARELHOS_03_000),
	TESTES_APARELHOS_04_000(MpTipoProduto.TESTES_APARELHOS, "Testes", null);
	
	private MpTipoProduto mpTipoProduto;
	private String descricao;
	private MpTipoProdutoCategoria mpTipoProdutoCategoria;
	
	// ---

	MpTipoProdutoCategoria(MpTipoProduto mpTipoProduto, String descricao,
													MpTipoProdutoCategoria mpTipoProdutoCategoria) {
		this.mpTipoProduto = mpTipoProduto;
		this.descricao = descricao;
		this.mpTipoProdutoCategoria = mpTipoProdutoCategoria;
	}
	
	public MpTipoProduto getMpTipoProduto() { return mpTipoProduto; }
	public String getDescricao() { return descricao; }
	public MpTipoProdutoCategoria getMpTipoProdutoCategoria() { return mpTipoProdutoCategoria; }
	
}